{% set khiops_version = "10.3.2-rc.0" %}
{% set version = khiops_version.replace("-", "") %}

package:
  name: khiops-binaries
  version: {{ version }}

source:
  url: https://github.com/KhiopsML/khiops/archive/refs/tags/{{ khiops_version }}.tar.gz
  sha256: 2321837b22b84567e7b3fd08a7963d540f4e03ec488fb0ebdca5ecc14bf9ef01
build:
  number: 0

requirements:
  build:
    - {{ mpi }}  # [mpi == 'openmpi' and build_platform != target_platform]
    - cmake
    - ninja
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - {{ mpi }}
  run:
    - {{ mpi }}

outputs:

# khiops-core package
  - name: khiops-core
    version: {{ version }}
    requirements:
      build:
        - cmake
        - ninja
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
      host:
        - {{ mpi }}
      run:
        - {{ mpi }}
    files:
      - bin/MODL*                    # [linux or osx]
      - bin/MODL_Coclustering*       # [linux or osx]
      - bin/_khiopsgetprocnumber     # [linux or osx]
      - bin/khiops_env               # [linux or osx]
      - bin/khiops                   # [linux or osx]
      - bin/khiops_coclustering      # [linux or osx]
      - Library/bin/khiops_env.cmd            # [win]
      - Library/bin/khiops.cmd                # [win]
      - Library/bin/khiops_coclustering.cmd   # [win]
      - Library/bin/MODL.exe                  # [win]
      - Library/bin/MODL_Coclustering.exe     # [win]
      - Library/bin/_khiopsgetprocnumber.exe  # [win]
    test:
      commands:
        - export KHIOPS_MPI_VERBOSE=true  # [linux or osx]
        - khiops_env --env
        - khiops -s
        - khiops_coclustering -s

# kni package (do not need khiops-core as a runtime dependency)
  - name: kni
    version: {{ version }}
    files:
      - lib/libKhiopsNativeInterface.so*                  # [linux]
      - lib/libKhiopsNativeInterface.{{ version }}.dylib  # [osx]
      - include/KhiopsNativeInterface.h                   # [linux or osx]
      - Library/bin/KhiopsNativeInterface.dll           # [win]
      - Library/lib/KhiopsNativeInterface.lib           # [win]
      - Library/include/KhiopsNativeInterface.h             # [win]
    requirements:
      build:
        - cmake
        - ninja
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
    test:
      commands:
        - test -f $PREFIX/lib/libKhiopsNativeInterface.so                   # [linux]
        - test -f $PREFIX/lib/libKhiopsNativeInterface.{{ version }}.dylib  # [osx]
        - if not exist %LIBRARY_LIB%\KhiopsNativeInterface.lib exit 1      # [win]
        - if not exist %LIBRARY_BIN%\KhiopsNativeInterface.dll exit 1      # [win]

about:
  home: https://khiops.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Khiops is an AutoML suite for supervised and unsupervised learning
  doc_url: https://khiops.org
  dev_url: https://github.com/khiopsml/khiops

extra:
  recipe-maintainers:
    - bruno-at-orange
